{
    "name": "Car Rental Booking",
    "summary": """Car Rental Booking""",
    "description": """Car Rental Booking""",
    "author": 'Sreya Sajeev',
    "website": '',
    "category": "demo",
    "version": "19.0.0.0",
    "license": "LGPL-3",
    "depends": ['base','mail',],
    "data": [
        "security/rental_groups.xml",
        "security/record_rules.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/vehicles_views.xml",
        "views/booking_views.xml",
        "views/partner_views.xml",
        "report/booking_templates.xml",
        "report/booking_report.xml",
        "data/mail_template.xml",
        # "wizard/booking_wizard.xml",
    ],
    "installable": True,
    "auto_install": True,
    "application": True,
}